# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "com.github/wojciech11/tester-centos"
  config.vm.define "tester-centos"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  #config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.memory = "4096"
     vb.name = "tester-centos"
   end

   config.vm.hostname = "tester-m"
  
  # View the documentation for the provider you are using for more
  # information on available options.

  TESTER_USER="tester"
  TESTER_PASSWORD="tester"

  tester_dir = <<-SHELL
    mkdir -p /var/opt/tester
  SHELL
  
  update_packages= <<-SHELL
    yum check-update
    yum -y upgrade
    yum install epel-release -y
  SHELL

  add_tester_user = <<-SHELL
  if [ ! -f /var/opt/tester/FLAG_#{TESTER_USER}_CREATED ]; then
    adduser --create-home -p "" #{TESTER_USER}
    usermod -a -G wheel #{TESTER_USER}
    echo "#{TESTER_USER}:#{TESTER_PASSWORD}" | chpasswd
    touch /var/opt/tester/FLAG_#{TESTER_USER}_CREATED
  fi
  SHELL

  install_pip = <<-SHELL
    if [ ! -f /var/opt/tester/FLAG_PIP_INSTALLED ]; then
      yum -y install python-pip && \
      pip install -U pip && \
      touch /var/opt/tester/FLAG_PIP_INSTALLED
    fi
  SHELL

  # gitg is the simplest gui for learnig
  # gitk is more advanced
  install_git_gui = <<-SHELL
    if [ ! -f /var/opt/tester/FLAG_GIT_GUI_INSTALLED ]; then
      yum -y install gitg &&
      yum -y install gitk && \
      touch /var/opt/tester/FLAG_GIT_GUI_INSTALLED
    fi
  SHELL

  install_dockerce = <<-SHELL
     if [ ! -f /var/opt/tester/FLAG_DOCKER_INSTALLED ]; then
        yum install -y yum-utils
        yum-config-manager \
           --add-repo \
           https://download.docker.com/linux/centos/docker-ce.repo

        yum makecache fast
        yum install docker-ce -y
        systemctl start docker && \
        touch /var/opt/tester/FLAG_DOCKER_INSTALLED
     fi
   SHELL

   install_atom = <<-SHELL
      if [ ! -f /var/opt/tester/FLAG_ATOM_INSTALLED ]; then
        wget https://github.com/atom/atom/releases/download/v1.22.1/atom.x86_64.rpm
        yum install atom.x86_64.rpm -y
        rm -f atom.x86_64.rpm
        touch /var/opt/tester/FLAG_ATOM_INSTALLED
      fi;
   SHELL

   install_nodejs = <<-SHELL
    echo "TODO: add NPM installer"
   SHELL

   install_chrome = <<-SHELL
    if [ ! -f /var/opt/tester/FLAG_CHROME_INSTALLED ]; then

      cat << EOF > /etc/yum.repos.d/google-chrome.repo
[google-chrome]
name=google-chrome - \$basearch
baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64/\$basearch
enabled=1
gpgcheck=1
gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
EOF
      yum install google-chrome-stable -y
      touch /var/opt/tester/FLAG_CHROME_INSTALLED
      fi;
   SHELL

   install_firefox = <<-SHELL
    if [ ! -f /usr/bin/firefox ]; then
      yum install firefox -y
    fi
   SHELL

   install_postman = <<-SHELL
    if [ ! -f /usr/bin/postman ]; then
      wget https://dl.pstmn.io/download/latest/linux64 -O postman.tar.gz && \
      tar -xzf postman.tar.gz -C /opt && \
      ln -s /opt/Postman/Postman /usr/bin/postman && \
      rm -f postman.tar.gz
    fi;
   SHELL

   install_jdk = <<-SHELL
      yum install java-1.8.0-openjdk-devel -y
   SHELL

   install_libreoffice = <<-SHELL
     yum install libreoffice -y
   SHELL

   install_android_studio = <<-SHELL
   if [ ! -d /home/#{TESTER_USER}/android-studio ]; then
       wget https://dl.google.com/dl/android/studio/ide-zips/3.0.0.18/android-studio-ide-171.4408382-linux.zip
       unzip android-studio-ide-171.4408382-linux.zip
       mv android-studio /home/#{TESTER_USER}
       rm android-studio-ide-171.4408382-linux.zip
       chown #{TESTER_USER}:#{TESTER_USER} /home/#{TESTER_USER}/android-studio -R
   fi;
   SHELL

   cleanup_cache = <<-SHELL
     yum clean all
     rm -rf /var/cache/yum
   SHELL

   for s in [tester_dir,
             update_packages,
             add_tester_user,
             install_pip,
             install_git_gui,
             install_dockerce,
             install_atom,
             install_chrome,
             install_firefox,
             install_postman,      
             install_nodejs,
             install_jdk,
             install_libreoffice,
             install_android_studio,
             cleanup_cache]
     config.vm.provision "shell", inline: s
    end

end
